name: Automation Release

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Branch to merge from"
        required: true
      target_branch:
        description: "Branch to merge into"
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: create_pull_request
        run: |
          CURRENT_TIME=$(date +"%Y-%m-%d")
          PR_TITLE="Autotmation Release: $CURRENT_TIME"
          PR_URL=$(gh pr create -B ${{ github.event.inputs.target_branch }} -H ${{ github.event.inputs.source_branch }} --title "$PR_TITLE" --body 'Created by Github action')
          echo "PR url: $PR_URL"
          if [[ "$PR_URL" == "ERROR" ]]; then
            echo "Failed to create PR"
            exit 1
          fi
          echo "pull-request-url=$PR_URL" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge Pull Request
        run: gh pr merge ${{ env.pull-request-url }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-post-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Make Changes
        run: |
          echo "## Post Release Update - ${{ env.date }}" >> README.md
          echo "" >> README.md
          echo "This is an automated update after the release on ${{ env.date }}." >> README.md
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Post release update on ${{ env.date }}"

      - name: Create Pull Request
        id: create_pull_request
        run: |
          CURRENT_TIME=$(date +"%Y-%m-%d")
          PR_TITLE="Autotmation Post Release: $CURRENT_TIME"
          PR_URL=$(gh pr create -B ${{ github.event.inputs.source_branch }} -H post-release --title "$PR_TITLE" --body 'Created by Github action')
          echo "PR url: $PR_URL"
          if [[ "$PR_URL" == "ERROR" ]]; then
            echo "Failed to create PR"
            exit 1
          fi
          echo "pull-request-url=$PR_URL" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge Pull Request
        run: gh pr merge ${{ env.pull-request-url }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
